In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns='has_covid'),
                                                df['has_covid'],
                                                test_size=0.2)

In [10]:
x_train.sample(5)

    age  gender  fever   cough       city
12   25  Female   99.0  Strong    Kolkata
15   70    Male  103.0  Strong    Kolkata
41   82    Male    NaN    Mild    Kolkata
68   54  Female  104.0  Strong    Kolkata
18   64  Female   98.0    Mild  Bangalore

# AAM Zindagi

In [11]:
'''
Task :
1. Handle Missing Value 
2. Encode Cat to Num cols :
 - gender , city -> Nominal Categoriclal -> One Hot Encoder
 - cough -> Ordinal Categorical -> Ordinal Encoder
3. Merge all sets into 1 data frame
'''

'\nTask :\n1. Handle Missing Value \n2. Encode Cat to Num cols :\n - gender , city -> Nominal Categoriclal -> One Hot Encoder\n - cough -> Ordinal Categorical -> Ordinal Encoder\n3. Merge all sets into 1 data frame\n'

In [12]:
# Fillin missing values 
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])                         
x_train_fever.shape

(80, 1)

In [14]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [17]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [19]:
 # Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age.shape

(80, 1)

In [20]:
# Merging all columns 
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)
x_train_transformed.shape

(80, 7)

# MENTOS Zindagi

In [21]:
from sklearn.compose import ColumnTransformer

In [39]:
trans = ColumnTransformer(transformers= [
                          ('tnf1',SimpleImputer(),['fever']),
                          ('tnf2',OneHotEncoder(sparse_output=False,drop='first'),['gender','city']),
                          ('tnf3 ',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']) 
                                         ] , remainder='passthrough')

In [43]:
'''
Syntax = ColumnTransformer(transformers= [
                          ('var_name','Function','coln name')
                                         ] , remainder='passthrough/drop')

'''

"\nSyntax = ColumnTransformer(transformers= [\n                          ('var_name','Function','coln name')\n                                         ] , remainder='passthrough/drop')\n\n"

In [44]:
trans.fit_transform(x_train).shape

(80, 7)

In [45]:
trans.fit_transform(x_test).shape

(20, 7)