In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('play_tennis.csv')

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df.drop(columns=['day'],inplace=True)

In [6]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [7]:
# Problem 1 

# Outlook = Sunny , Temp = Hot ,Humidity = High ,Wind = Weak 
# Play = Yes or No ??

In [9]:
# Soln : 

# P(Yes | Sunny,Hot,Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) 

# P(No | Sunny,Hot,Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) 

# Compare & decide using the Maximum a Posteriori Rule

In [10]:
# Problem 2 

# Outlook = Overcast , Temp = Cold , Humidity = Low , Wind = Weak 
# Play = Yes or No ??

In [11]:
# Soln : 

# P(Yes | Overcast,Cold,Low,Weak) = P(Overcast| Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) 

# P(No | Overcast,Cold,Low,Weak) = P(Overcast| No) * P(Cold | No) * P(Low | No) * P(Weak | No) 

# Compare & decide using the Maximum a Posteriori Rule

In [12]:
# How Navie Byes Model Works 

# Training  

# Lookup table (Dictionary) 

#  Testing

In [14]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [16]:
py = 9/14 
pn = 5/14

print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [18]:
#  OutLook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [19]:
# Outlook probabilities given No
pSN = 3 / 5   # Sunny | No
pON = 0 / 5   # Overcast | No
pRN = 2 / 5   # Rainy | No

# Outlook probabilities given Yes
pOY = 4 / 9   # Overcast | Yes
pRY = 3 / 9   # Rainy | Yes
pSY = 2 / 9   # Sunny | Yes

In [22]:
# Crosstab for Temperature vs Play
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [23]:
# Temperature probabilities given No
pCoolN = 1 / 5
pHotN = 2 / 5
pMildN = 2 / 5

# Temperature probabilities given Yes
pCoolY = 3 / 9
pHotY = 2 / 9
pMildY = 4 / 9

In [24]:
# Crosstab for Humidity vs Play
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [25]:
# Humidity probabilities given No
pHighN = 4 / 5
pNormalN = 1 / 5

# Humidity probabilities given Yes
pHighY = 3 / 9
pNormalY = 6 / 9

In [26]:
# Crosstab for Wind vs Play
pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [27]:
# Wind probabilities given No
pStrongN = 3 / 5
pWeakN = 2 / 5

# Wind probabilities given Yes
pStrongY = 3 / 9
pWeakY = 6 / 9

In [33]:
# Formula: P(Yes) * P(Sunny|Yes) * P(Hot|Yes) * P(High|Yes) * P(Weak|Yes)
pYes = py * pSY * pHotY * pHighY * pWeakY
print("Score for Yes:", pYes)

Score for Yes: 0.007054673721340388

In [34]:
# Formula: P(No) * P(Sunny|No) * P(Hot|No) * P(High|No) * P(Weak|No)
pNo = pn * pSN * pHotN * pHighN * pWeakN
print("Score for No:", pNo)

Score for No: 0.02742857142857143

In [35]:
# Prob 1 soln is No