## 🔢 Numerical Transformation (Numerical Columns)
 There are mainly two types of transformations:

### 1️⃣ Discretization (Binning / Bracket Binning)
 - Converts continuous numerical values into discrete intervals (bins).
 - Helps in simplifying data and handling non-linear relationships.
 - Example: Age → [0-18], [19-35], [36-60], [60+]

### 2️⃣ Binarization
 - Converts numerical values into binary form (0 or 1) based on a threshold.
 - Useful for presence/absence or yes/no type features.
 - Example: Salary > 50000 → 1, else → 0

In [2]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier

from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','SibSp','Parch','Survived'])
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [6]:
df.dropna(inplace=True)

In [8]:
df['Family'] = df['SibSp'] + df['Parch']

In [9]:
df.sample(3)

     Survived   Age  SibSp  Parch     Fare  Family
638         0  41.0      0      5  39.6875       5
59          0  11.0      5      2  46.9000       7
81          1  29.0      0      0   9.5000       0

In [10]:
df.drop(columns=['SibSp','Parch'],inplace= True)

In [11]:
df.sample(3)

     Survived   Age   Fare  Family
11          1  58.0  26.55       0
383         1  35.0  52.00       1
595         0  36.0  24.15       2

In [12]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

Without Binarization

In [20]:
clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

accuracy_score(y_test,y_pred)

0.6153846153846154

In [21]:
np.mean(cross_val_score(clf,x,y,cv=15,scoring='accuracy'))

np.float64(0.6276004728132387)

Applying Binarization

In [22]:
from sklearn.preprocessing import Binarizer   #Binarization

In [23]:
# We are gonna apply bins on Family column to find if 
# passenger is travelling Alone (Famile = 0) or With family (Family != 0)
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['Family'])
],remainder = 'passthrough')

In [24]:
x_train_trans = trf.fit_transform(x_train)
x_test_trans = trf.transform(x_test)

In [27]:
pd.DataFrame(x_train_trans,columns=['family','Age','Fare'])

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [30]:
clf1 = DecisionTreeClassifier()

clf1.fit(x_train,y_train)
y_pre2 = clf.predict(x_test)

accuracy_score(y_test,y_pre2)

0.6153846153846154

In [31]:
np.mean(cross_val_score(clf1,x,y,cv=15,scoring='accuracy'))

np.float64(0.6388297872340425)