# KNN Imputer
https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html 
## Advantages
- Performs better than mean, median, and mode imputation in most cases.
- Preserves relationships and patterns between features.
- Uses nearest neighboring data points for more realistic imputations.

## Disadvantages
- Computationally expensive because it performs many distance calculations.
- Slow on large datasets.
- Requires more memory/storage in production since training data is needed for neighbor calculations.

## Important Notes
- Default missing values are represented using `np.nan`.
- `weights='uniform'` gives equal importance to neighbors.
- `weights='distance'` gives more importance to closer neighbors using reciprocal distance.

In [1]:
import numpy as np 
import pandas as pd  

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer ,KNNImputer 

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [6]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [7]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [8]:
x_train , x_test ,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
x_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [10]:
# Simple Imputer -> Mean 
si = SimpleImputer()

x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)

In [11]:
# Training 
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)
y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.7374301675977654

In [28]:
# Now KNN imputation 
knn = KNNImputer(n_neighbors=5, weights='uniform')

x_train_trf2 = knn.fit_transform(x_train)
x_test_trf2 = knn.transform(x_test)

In [29]:
# Training 
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)
y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.7430167597765364

In [ ]:
# KNN > other imputors